### ISSUE TITLE
Dil ve tercüme/Translate

### ISSUE THREAD

**Issue by 40345839668** [MicrosoftDocs/xamarin-docs.tr-tr#1]
https://www.bing.com/translator/?ref=SALL&br=ro
ile farklı diller kulanılabilir.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: b744a13f-16ad-4f35-cdf2-bdfd6fa90df1
* Version Independent ID: 7a08549b-07a5-085b-0c93-255d9e84d7a3
* Content: [Xamarin.Forms görsel durum Yöneticisi - Xamarin](https://docs.microsoft.com/tr-tr/xamarin/xamarin-forms/user-interface/visual-state-manager)
* Content Source: [docs/xamarin-forms/user-interface/visual-state-manager.md](https://github.com/MicrosoftDocs/xamarin-docs.tr-TR/blob/live/docs/xamarin-forms/user-interface/visual-state-manager.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by CeciAc** [comment]
Merhaba, @40345839668, 

Geri bildiriminiz için teşekkür ederiz. 

Yorumlarınızı etkin olarak inceliyoruz ve yakında size döneceğiz. 

Saygılarımla, 
Microsoft DOCS Uluslararası Ekibi

**Comment by CeciAc** [comment]
Merhaba @40345839668

Geri bildiriminiz için teşekkür ederiz. Söz konusu sayfada makine çevirisi yapılmıştır, bu nedenle içerik tam olarak anlaşılır olmayabilir. Yakın zamanda sağ tarafa “İngilizce Dilinde Oku” seçeneği ekledik, bu seçeneği kullanarak dil ayarlarını değiştirmeden İngilizce sürüme geçebilirsiniz. 

Saygılarımla, 

Microsoft DOCS Uluslararası Ekibi

**Comment by 40345839668** [comment]
I wish I was aware
